In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('/content/hospital_patients_real_world.csv')

# Display the first 5 rows of the DataFrame
print("First 5 rows of the dataset:")
display(df.head())

# Display general information about the DataFrame, including data types and non-null values
print("\nDataFrame Information:")
df.info()

First 5 rows of the dataset:

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PatientID      5000 non-null   object
 1   Age            4650 non-null   float64
 2   Gender         4650 non-null   object
 3   Diagnosis      4650 non-null   object
 4   AdmissionDate  5000 non-null   object
 5   DischargeDate  5000 non-null   object
 6   HospitalID     5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

### Handle Missing Data

Let's detect missing values and then apply a basic strategy to handle them. For simplicity, we'll drop rows that contain any missing values. In a real-world scenario, you might choose to impute missing values (e.g., with the mean, median, or mode) depending on the nature of the data and the column.

In [2]:
# Detect missing values
print("\nNumber of missing values per column (before handling):")
display(df.isnull().sum())

# Handle missing values: Drop rows with any missing values
df_cleaned = df.dropna()

print("\nNumber of missing values per column (after dropping rows with any NaNs):")
display(df_cleaned.isnull().sum())

print(f"\nOriginal number of rows: {len(df)}")
print(f"Number of rows after dropping NaNs: {len(df_cleaned)}")

display(df_cleaned.head())

Number of missing values per column (before handling):

PatientID          0
Age              350
Gender           350
Diagnosis        350
AdmissionDate      0
DischargeDate      0
HospitalID         0
dtype: int64

Number of missing values per column (after dropping rows with any NaNs):

PatientID        0
Age              0
Gender           0
Diagnosis        0
AdmissionDate    0
DischargeDate    0
HospitalID       0
dtype: int64

Original number of rows: 5000
Number of rows after dropping NaNs: 4005

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

### Detect and Filter Outliers

For detecting outliers, a common simple method is to use the Interquartile Range (IQR). Values that fall below `Q1 - 1.5 * IQR` or above `Q3 + 1.5 * IQR` are considered outliers. We'll apply this to a numerical column, for example, 'Age' or any relevant numerical column available in your dataset. If the dataset does not have suitable numerical columns for outlier detection, you may need to adjust the column selection.

Let's assume 'Age' is a numerical column suitable for outlier detection. If not, please replace 'Age' with an appropriate numerical column name from your dataset (e.g., 'Pulse Rate', 'Weight', etc.).

In [3]:
# Identify a numerical column for outlier detection (e.g., 'Age')
# Please adjust 'numerical_column' if 'Age' is not suitable or doesn't exist
numerical_column = 'Age' # Or 'Pulse Rate', 'Weight', etc.

# Check if the column exists and is numeric
if numerical_column in df_cleaned.columns and pd.api.types.is_numeric_dtype(df_cleaned[numerical_column]):
    print(f"\nDetecting outliers in the '{numerical_column}' column using IQR method...")

    Q1 = df_cleaned[numerical_column].quantile(0.25)
    Q3 = df_cleaned[numerical_column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df_cleaned[(df_cleaned[numerical_column] < lower_bound) | (df_cleaned[numerical_column] > upper_bound)]
    df_no_outliers = df_cleaned[(df_cleaned[numerical_column] >= lower_bound) & (df_cleaned[numerical_column] <= upper_bound)]

    print(f"Number of outliers detected in '{numerical_column}': {len(outliers)}")
    print(f"Original number of rows in cleaned data: {len(df_cleaned)}")
    print(f"Number of rows after filtering outliers: {len(df_no_outliers)}")

    print(f"\nOutliers in '{numerical_column}':")
    display(outliers.head())

    print(f"\nDataFrame after removing outliers in '{numerical_column}':")
    display(df_no_outliers.head())

else:
    print(f"Column '{numerical_column}' not found or is not numeric. Please choose a valid numerical column for outlier detection.")
    print("Available columns:", df_cleaned.columns.tolist())

Detecting outliers in the 'Age' column using IQR method...
Number of outliers detected in 'Age': 0
Original number of rows in cleaned data: 4005
Number of rows after filtering outliers: 4005

Outliers in 'Age':

Empty DataFrame
Columns: [PatientID, Age, Gender, Diagnosis, AdmissionDate, DischargeDate, HospitalID]
Index: []

DataFrame after removing outliers in 'Age':

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

### 1. Load Data and Initial Overview (Simple)

In [4]:
import pandas as pd

df_simple = pd.read_csv('/content/hospital_patients_real_world.csv')

print("First 5 rows:")
display(df_simple.head())

print("\nMissing values per column (count):")
display(df_simple.isnull().sum())

First 5 rows:

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

Missing values per column (count):

PatientID          0
Age              350
Gender           350
Diagnosis        350
AdmissionDate      0
DischargeDate      0
HospitalID         0
dtype: int64

### 2. Handle Missing Data (Simple)

This code drops any row that contains at least one missing value. This is a quick way to clean the data, but for some datasets, imputation (filling missing values with estimates) might be more suitable.

In [5]:
# Drop rows with any missing values
df_cleaned_simple = df_simple.dropna()

print(f"Original rows: {len(df_simple)}")
print(f"Rows after dropping NaNs: {len(df_cleaned_simple)}")

print("\nMissing values after cleaning:")
display(df_cleaned_simple.isnull().sum())

Original rows: 5000
Rows after dropping NaNs: 4005

Missing values after cleaning:

PatientID        0
Age              0
Gender           0
Diagnosis        0
AdmissionDate    0
DischargeDate    0
HospitalID       0
dtype: int64

### 3. Detect and Filter Outliers (Simple)

We'll use the Interquartile Range (IQR) method for a numerical column. This method defines outliers as values significantly outside the 'middle 50%' of the data. For this example, we'll use the 'Age' column. If 'Age' is not present or not numeric, please update the `numerical_column` variable to another suitable column.

In [6]:
numerical_column_simple = 'Age' # Change if needed

if numerical_column_simple in df_cleaned_simple.columns and pd.api.types.is_numeric_dtype(df_cleaned_simple[numerical_column_simple]):
    Q1 = df_cleaned_simple[numerical_column_simple].quantile(0.25)
    Q3 = df_cleaned_simple[numerical_column_simple].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers_mask = (df_cleaned_simple[numerical_column_simple] < lower_bound) | \
                    (df_cleaned_simple[numerical_column_simple] > upper_bound)
    outliers_count = outliers_mask.sum()

    # Filter out outliers
    df_no_outliers_simple = df_cleaned_simple[~outliers_mask]

    print(f"Outliers in '{numerical_column_simple}': {outliers_count} rows")
    print(f"Data size after removing outliers: {len(df_no_outliers_simple)} rows")

    print(f"\nFirst 5 rows after removing outliers in '{numerical_column_simple}':")
    display(df_no_outliers_simple.head())
else:
    print(f"Column '{numerical_column_simple}' not found or is not numeric. Available columns: {df_cleaned_simple.columns.tolist()}")

Outliers in 'Age': 0 rows
Data size after removing outliers: 4005 rows

First 5 rows after removing outliers in 'Age':

,PatientID,Age,Gender,Diagnosis,AdmissionDate,DischargeDate,HospitalID
0,PN-2021066,7.0,Other,Myocardial Infarction,2024-03-23,2024-03-29,HOSP-65
1,PN-4606019,36.0,Other,Pneumonia,2024-08-01,2024-08-07,HOSP-79
2,PN-2594016,70.0,Other,Influenza,2024-11-16,2024-11-23,HOSP-27
3,PN-6906914,90.0,Unknown,Acute Bronchitis,2025-07-05,2025-07-10,HOSP-64
4,PN-4656204,0.0,Female,Type 2 Diabetes,2023-08-30,2023-08-31,HOSP-31

In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv("hospital_patients_real_world.csv")

print(df.isnull().sum())

PatientID          0
Age              350
Gender           350
Diagnosis        350
AdmissionDate      0
DischargeDate      0
HospitalID         0
dtype: int64

In [10]:
import pandas as pd
import numpy as np

df = pd.read_csv("hospital_patients_real_world.csv")

Q1 = df["Age"].quantile(.25)
Q3 = df["Age"].quantile(.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)
print("Lower limit =", lower)
print("Upper limit =", upper)

outliers = df[(df["Age"] < lower) | (df["Age"] > upper)]

print("\nNumber of outliers =", len(outliers))

Q1 = 23.0
Q3 = 72.0
IQR = 49.0
Lower limit = -50.5
Upper limit = 145.5

Number of outliers = 0